cookie:
  expiry_days: 30
  key: random_signature_key
  name: some_cookie_name
credentials:
  usernames:
    nio_admin:
      email: admin@admin.com
      name: Administrador
      password: $2b$12$EjlkciIBJ/ZCPKT4YX2VfObtU62ewDFqPDR51INEYhvvzJA08tFNi
pre-authorized:
  emails:
  - admin@admin.com
