version: '3.8'

services:
  consultas-sap-ai:
    build: .
    image: consultas-sap-aut:latest
    container_name: consultas-sap-aut
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
    volumes:
      - db_data:/app/data
      - kb_data:/app/knowledge_base
    restart: unless-stopped

volumes:
  db_data:
  kb_data:
